name: Docker Image CI

env:
  CONTAINER_REGISTRY: "ghcr.io"
  
on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  get-timestamp:
    runs-on: self-hosted
    outputs:
      timestamp: ${{ steps.return.outputs.timestamp }}
    steps:
      - id: return
        run: echo "timestamp=$(date +"%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT

  get-version:
    runs-on: self-hosted
    needs: get-timestamp
    outputs:
      version: ${{ steps.return.outputs.version }}
    steps:
    - if: github.event_name == 'release'
      run: echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
    - if: github.event_name != 'release'
      run: echo "VERSION=${{ needs.get-timestamp.outputs.timestamp }}" >> $GITHUB_ENV
    - id: return
      run: echo "version=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"

  get-base-tag:
    runs-on: self-hosted
    outputs:
      base-tag: ${{ steps.return.outputs.base-tag }}
    steps:
      - id: return
        run: echo "base-tag=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}" >> $GITHUB_OUTPUT

  get-version-tag:
    runs-on: self-hosted
    needs: [get-version, get-base-tag]
    outputs:
      version-tag: ${{ steps.return.outputs.version-tag }}
    steps:
      - id: return
        run: echo "version-tag=${{ needs.get-base-tag.outputs.base-tag }}:${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT

  get-latest-tag:
    runs-on: self-hosted
    needs: [get-base-tag]
    outputs:
      latest-tag: ${{ steps.return.outputs.latest-tag }}
    steps:
      - id: return
        run: echo "latest-tag=${{ needs.get-base-tag.outputs.base-tag }}:latest" >> $GITHUB_OUTPUT

  build:
    name: Build Docker image
    runs-on: self-hosted
    needs: [get-version-tag, get-latest-tag]
    steps:
      - uses: actions/checkout@v4
      - run: docker build . --no-cache --file Dockerfile --tag ${{ needs.get-version-tag.outputs.version-tag }} --tag ${{  needs.get-latest-tag.outputs.latest-tag }}

  publish:
    name: Publish Docker image to container registry
    needs: [get-version-tag, get-latest-tag, build]
    runs-on: self-hosted
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{env.CONTAINER_REGISTRY}}
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - run: docker push ${{ needs.get-version-tag.outputs.version-tag }}
      - run: docker push ${{ needs.get-latest-tag.outputs.latest-tag }}
